title: <p align="center"> Archana Taneja </p>
logo: /assets/img/Archana_Photo_edited.jpg
description: <p align="center">
  <a href="/assets/Resume_Archana Taneja_2022.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/archana-taneja-ba92a1ba/">LinkedIn</a> |
  <a href="https://github.com/Archi1994/">GitHub</a> 
  I'm working as a UI Developer and a Security Expert for my team in SAP Labs. I have interest in Machine Learning.
  I have done projects on Indian sign language detection using matlab and Event Detection from tweets. 
  Currently am pursuing Executive PG Programme in Machine Learning & AI offered by Upgrad and IIIT-Bangalore.
  Hope this will help me grow more in the field of Data Science. This is the page I will be using to host my upcoming projects done in the field of Data Science.
  </p>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
